name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '6.9.5'

      - name: Install Dependency
        run: |
          npm install --production --silent
          sed -i '46,51d' node_modules/hexo/lib/plugins/generator/post.js

      - name: Build Web
        run: |
          sh bin/release.sh
          cp -r ./resource/* ./public/
          cp -r ./posts/book ./public/
          test -s public/index_en.html

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: 'tengine-opensource'
          user_email: 'tengine-opensource@alibaab-inc.com'
          external_repository: alibaba/tengine-website
          publish_branch: master
          publish_dir: ./public
          full_commit_message: update page automatically

